import { CheckCircle2, CircleMinus, Dog, Folder, Info, MoreVertical, PawPrint, Pencil, Plus, Search, Users, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { useNavigate } from 'react-router-dom';
import { useConfig } from '../context/ConfigContext.jsx';

const counts = { Labrador: 22, 'Golden Retriever': 14, 'Pastor Alemão': 8, Poodle: 4, Outra: 0, Cão: 48 };

export default function AnimalRegistryPage({ activeTab }) {
  const navigate = useNavigate();
  const { animalTypes, dogBreeds, addDogBreed, updateDogBreed, toggleDogBreed, addAnimalType, toggleAnimalType } = useConfig();
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('all');
  const [animalFilter, setAnimalFilter] = useState('all');
  const [dialog, setDialog] = useState(null);
  const records = activeTab === 'breeds' ? dogBreeds : animalTypes;
  const filtered = useMemo(() => records.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || item.active === (status === 'active')) && (activeTab === 'types' || animalFilter === 'all' || (item.animalType || 'Cão') === animalFilter)), [records, query, status, animalFilter, activeTab]);
  const activeCount = records.filter((item) => item.active).length;
  const linked = records.reduce((total, item) => total + (counts[item.name] || 0), 0);

  function saveBreed(data) { if (dialog?.breed) updateDogBreed(dialog.breed.name, data); else addDogBreed(data); setDialog(null); }
  return <section className="screen animal-registry-screen animate-in">
    <header><p className="eyebrow">Configurações</p><h2>Raças e tipos de animais</h2><p>Gerencie os tipos de animais aceitos no sistema e as raças disponíveis no cadastro.</p></header>
    <div className="animal-registry-tabs"><button className={activeTab === 'types' ? 'active' : ''} onClick={() => navigate('/config/tipos-animais')}><PawPrint size={18} /> Tipos de animais <b>{animalTypes.length}</b></button><button className={activeTab === 'breeds' ? 'active' : ''} onClick={() => navigate('/config/racas')}><Dog size={18} /> Raças <b>{dogBreeds.length}</b></button><button className="primary-action" onClick={() => activeTab === 'breeds' ? setDialog({ breed: null }) : setDialog({ type: null })}><Plus size={18} /> {activeTab === 'breeds' ? 'Nova raça' : 'Novo tipo'}</button></div>
    <section className="animal-registry-panel"><div className="registry-summary"><article><Folder /><span><strong>{records.length}</strong>{activeTab === 'breeds' ? 'raças cadastradas' : 'tipos cadastrados'}</span></article><article><CheckCircle2 /><span><strong>{activeCount}</strong>ativos</span></article><article><CircleMinus /><span><strong>{records.length - activeCount}</strong>desativados</span></article><article><Users /><span><strong>{linked || 48}</strong>animais vinculados</span></article></div>
      <div className="registry-filters"><label><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={activeTab === 'breeds' ? 'Buscar raça' : 'Buscar tipo de animal'} /></label>{activeTab === 'breeds' && <select value={animalFilter} onChange={(e) => setAnimalFilter(e.target.value)}><option value="all">Todos os tipos de animais</option>{animalTypes.map((type) => <option key={type.name}>{type.name}</option>)}</select>}<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Todos os status</option><option value="active">Ativos</option><option value="inactive">Desativados</option></select></div>
      {activeTab === 'breeds' ? <BreedTable records={filtered} onEdit={(breed) => setDialog({ breed })} onToggle={toggleDogBreed} /> : <TypeTable records={filtered} breeds={dogBreeds} onEdit={(type) => navigate(`/config/tipos-animais/${encodeURIComponent(type.name)}/editar`)} onToggle={toggleAnimalType} />}
      <p className="registry-count">Exibindo {filtered.length} de {records.length} {activeTab === 'breeds' ? 'raças' : 'tipos'}</p>
    </section>
    <aside className="registry-note"><Info size={20} /> {activeTab === 'breeds' ? 'Cada raça deve estar vinculada a um tipo de animal. Desativar uma raça impede sua seleção em novos cadastros, sem alterar os animais existentes.' : 'Os tipos de animais definem quais espécies podem ser cadastradas e quais raças ficam disponíveis.'}</aside>
    {dialog?.breed !== undefined && <BreedDialog breed={dialog.breed} animalTypes={animalTypes} onClose={() => setDialog(null)} onSave={saveBreed} />}
    {dialog?.type !== undefined && <QuickTypeDialog onClose={() => setDialog(null)} onSave={(data) => { addAnimalType(data); setDialog(null); }} />}
  </section>;
}

function BreedTable({ records, onEdit, onToggle }) { return <div className="registry-table"><div className="registry-row header"><span>Raça</span><span>Tipo de animal</span><span>Animais cadastrados</span><span>Disponível no cadastro</span><span>Status</span><span>Ações</span></div>{records.map((breed) => <article className="registry-row" key={breed.name}><strong><Dog />{breed.name === 'Outra' ? 'Sem raça definida' : breed.name}</strong><span>{breed.animalType || 'Cão'}</span><span>{counts[breed.name] || 0} animais</span><span>{breed.available === false ? 'Não' : 'Sim'}</span><Status active={breed.active} /><div className="registry-actions"><button onClick={() => onEdit(breed)}><Pencil size={15} /> Editar</button><button onClick={() => onToggle(breed.name)}><MoreVertical size={17} /></button></div></article>)}</div>; }
function TypeTable({ records, breeds, onEdit, onToggle }) { return <div className="registry-table type-table"><div className="registry-row header"><span>Tipo de animal</span><span>Raças vinculadas</span><span>Animais cadastrados</span><span>Disponível</span><span>Status</span><span>Ações</span></div>{records.map((type) => { const breedCount = breeds.filter((breed) => (breed.animalType || 'Cão') === type.name).length; return <article className="registry-row" key={type.name}><strong><PawPrint />{type.name}</strong><span>{breedCount} raças</span><span>{counts[type.name] || 0} animais</span><span>{type.active ? 'Sim' : 'Não'}</span><Status active={type.active} /><div className="registry-actions"><button onClick={() => onEdit(type)}><Pencil size={15} /> Editar</button><button onClick={() => onToggle(type.name)}><MoreVertical size={17} /></button></div></article>; })}</div>; }
function Status({ active }) { return <span className={`registry-status ${active ? 'active' : ''}`}>{active ? <CheckCircle2 size={14} /> : <CircleMinus size={14} />}{active ? 'Ativa' : 'Desativada'}</span>; }

function BreedDialog({ breed, animalTypes, onClose, onSave }) { const [form, setForm] = useState(breed || { name: '', animalType: animalTypes[0]?.name || 'Cão', available: true, active: true }); const update = (field, value) => setForm((current) => ({ ...current, [field]: value })); return createPortal(<div className="cycle-dialog-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="cycle-dialog registry-dialog" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><header><div><p className="eyebrow">Cadastro de raças</p><h2>{breed ? 'Editar raça' : 'Nova raça'}</h2></div><button type="button" onClick={onClose}><X /></button></header><section className="cycle-form-grid"><label className="wide"><span>Nome da raça *</span><input required value={form.name} onChange={(e) => update('name', e.target.value)} placeholder="Ex.: Labrador" /></label><label><span>Tipo de animal *</span><select value={form.animalType} onChange={(e) => update('animalType', e.target.value)}>{animalTypes.map((type) => <option key={type.name}>{type.name}</option>)}</select></label><label className="cycle-checkbox"><input type="checkbox" checked={form.available !== false} onChange={(e) => update('available', e.target.checked)} /> Disponível no cadastro</label></section><footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary-action">Salvar raça</button></footer></form></div>, document.body); }
function QuickTypeDialog({ onClose, onSave }) { const [form, setForm] = useState({ name: '', label: '', plural: '', description: '', active: true }); return createPortal(<div className="cycle-dialog-backdrop"><form className="cycle-dialog registry-dialog" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><header><div><p className="eyebrow">Tipos de animais</p><h2>Novo tipo de animal</h2></div><button type="button" onClick={onClose}><X /></button></header><section className="cycle-form-grid"><label><span>Nome do tipo *</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>Nome no plural</span><input value={form.plural} onChange={(e) => setForm({ ...form, plural: e.target.value })} /></label><label className="wide"><span>Descrição</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></section><footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary-action">Salvar tipo</button></footer></form></div>, document.body); }
